/* ============================================================
 * LIFE RPG - 全局配置
 * 所有"可以修改"的东西都集中在这里。
 * 页面代码不会写死任何奖励数字，全部读取这里或用户自建数据。
 * ============================================================ */

const CONFIG = {
  // localStorage 存储键
  storageKey: 'life_rpg_save_v1',

  /* ---------- 等级公式（集中管理，可自行调整成长速度） ----------
   * 每级所需 EXP = round(base * growth ^ (level - 1))
   * Lv.1→2 = 1000；Lv.2→3 = 1150；Lv.3→4 = 1323 ...
   * 想改快慢：调 base（基础值）或 growth（每级倍率 1 = 不增长）
   */
  level: {
    base: 1000,
    growth: 1.15,
    maxLevel: 999,
  },

  /* ---------- 四大属性（顺序即展示顺序） ----------
   * milestone 仅为进度条展示用的参考值，可随意修改
   */
  attributes: [
    { key: 'health',        name: 'Health',        zh: '体质', icon: '❤️', color: '#ff5c7a', milestone: 100 },
    { key: 'intelligence',  name: 'Intelligence',  zh: '智力', icon: '🧠', color: '#5cc8ff', milestone: 100 },
    { key: 'fitness',       name: 'Fitness',       zh: '体能', icon: '💪', color: '#ffc24b', milestone: 100 },
    { key: 'discipline',    name: 'Discipline',    zh: '自律', icon: '🎯', color: '#b07cff', milestone: 100 },
  ],

  /* ---------- 奖励方式 ---------- */
  rewardTypes: {
    fixed:    { name: '固定奖励', desc: '每完成一次，获得固定奖励' },
    per_unit: { name: '按数量',   desc: '按填写的数量计算，例如每 1 公里' },
    per_time: { name: '按时间',   desc: '按记录的分钟数计算，例如每 30 分钟' },
  },

  /* ---------- 成就 / 称号 可用的条件类型 ---------- */
  conditionTypes: {
    first_complete:    { name: '第一次完成',   needs: ['behaviorId'],        desc: '第一次完成某个行为' },
    total_count:       { name: '累计次数',     needs: ['behaviorId', 'value'], desc: '某行为累计完成 N 次' },
    total_quantity:    { name: '累计数量',     needs: ['behaviorId', 'value'], desc: '某行为累计完成 N 个单位' },
    total_completions: { name: '累计完成所有行为', needs: ['value'],          desc: '所有行为累计完成 N 次' },
    level:             { name: '达到等级',     needs: ['value'],             desc: '玩家等级达到 Lv.N' },
    attribute:         { name: '属性达到',     needs: ['attribute', 'value'], desc: '某项属性 ≥ N' },
    streak:            { name: '连续天数',     needs: ['behaviorId', 'value'], desc: '连续 N 天完成某行为' },
  },

  /* ---------- 创建行为/商品时的快捷图标 ---------- */
  iconPresets: [
    '📖','🏃','🌙','💪','🧠','🎯','💧','🥗','🍳','🥦','⚽','🏀',
    '🏊','🚴','🚶','🏋️','🤸','🧗','⛳','🏓','🏸','🎱','✍️','💻',
    '🎨','🎸','🎹','🎤','📷','🧘','🛏️','🧹','📝','🗣️','🌱','🌸',
    '☀️','🛁','🦷','🧴','🌍','✈️','🚆','🀄','🧋','🎬','🎮','🍩',
    '🍰','☕','🍷','🍔','🍕','🍣','🍦','🛍️','🎁','🛒','💰','💎',
    '⭐','🏆','👑','🔥','🎖️','🏅','🥇','🧭','🗝️','🛡️','🐉','🌿',
    '📚','✏️','🧮','🔬','🔭','🧪','💊','🩺','⚖️','📐','📏','📋',
    '🏕️','🏖️','🚗','🏍️','⛵','🚂','🗽','🏯','🎡','🎢','🎪','🎰',
    '🐶','🐱','🐦','🐟','🌻','🍀','🔮','🪐','⚡','🌟','💫','🌙',
  ],

  /* ---------- 首次打开时的示例内容（全部可编辑/删除/重建，只是模板） ---------- */
  seed: {
    categories: [
      { id: 'cat_study',   name: '学习', icon: '📚' },
      { id: 'cat_sport',   name: '运动', icon: '🏃' },
      { id: 'cat_life',    name: '生活', icon: '🌙' },
      { id: 'cat_work',    name: '工作', icon: '💼' },
      { id: 'cat_hobby',   name: '兴趣', icon: '🎨' },
      { id: 'cat_other',   name: '其他', icon: '📦' },
    ],

    behaviors: [
      {
        id: 'bh_read',
        name: '阅读',
        categoryId: 'cat_study',
        icon: '📖',
        description: '翻开一本书，和作者来一场跨越时空的对话',
        unit: '分钟',
        rewardType: 'per_time',
        perTimeMinutes: 30,
        rewards: { exp: 20, coins: 5, health: 0, intelligence: 1, fitness: 0, discipline: 0 },
      },
      {
        id: 'bh_run',
        name: '跑步',
        categoryId: 'cat_sport',
        icon: '🏃',
        description: '系好鞋带，让风成为你的配速员',
        unit: '公里',
        rewardType: 'per_unit',
        perTimeMinutes: 30,
        rewards: { exp: 20, coins: 5, health: 0, intelligence: 0, fitness: 1, discipline: 0 },
      },
      {
        id: 'bh_sleep',
        name: '早睡',
        categoryId: 'cat_life',
        icon: '🌙',
        description: '放下手机，把今天的故事交给梦境续写',
        unit: '次',
        rewardType: 'fixed',
        perTimeMinutes: 30,
        rewards: { exp: 30, coins: 10, health: 1, intelligence: 0, fitness: 0, discipline: 2 },
      },
    ],

    shopItems: [
      { id: 'sh_song',    name: '听一首歌',     icon: '🎧', description: '给耳朵发一颗糖，三分钟的 mini 假期', price: 10 },
      { id: 'sh_milktea', name: '喝杯奶茶',     icon: '🧋', description: '一杯下肚，烦恼被珍珠嚼碎',           price: 50 },
      { id: 'sh_game',    name: '游戏时间',     icon: '🎮', description: '按下开始键，把压力交给通关',           price: 80 },
      { id: 'sh_movie',   name: '看一场电影',   icon: '🎬', description: '两小时的逃离现实体验券',               price: 100 },
      { id: 'sh_meal',    name: '吃顿好的',     icon: '🍽️', description: '认真对待一顿饭，就是认真对待自己',     price: 200 },
      { id: 'sh_gift',    name: '给自己买礼物', icon: '🎁', description: '奖励过去一段时间里那个努力的自己',     price: 300 },
    ],

    achievements: [
      {
        id: 'ach_first',
        name: '初来乍到',
        icon: '🌟',
        description: '旅程的起点，总是从第一步开始',
        condition: { type: 'total_completions', behaviorId: '', attribute: '', value: 1 },
        rewards: { exp: 100, coins: 20 },
      },
      {
        id: 'ach_read10',
        name: '读书入门',
        icon: '📚',
        description: '十次翻开书本，世界比昨天大了一点点',
        condition: { type: 'total_count', behaviorId: 'bh_read', attribute: '', value: 10 },
        rewards: { exp: 200, coins: 50 },
      },
      {
        id: 'ach_streak3',
        name: '三日之约',
        icon: '🔥',
        description: '连续三天，你已经和惰性交过手并赢了',
        condition: { type: 'streak', behaviorId: 'bh_run', attribute: '', value: 3 },
        rewards: { exp: 300, coins: 80 },
      },
      {
        id: 'ach_bookworm',
        name: '书虫',
        icon: '🐛',
        description: '书架在变厚，大脑也在变厚',
        condition: { type: 'total_count', behaviorId: 'bh_read', attribute: '', value: 30 },
        rewards: { exp: 500, coins: 100 },
      },
      {
        id: 'ach_runner',
        name: '跑者',
        icon: '👟',
        description: '你的鞋底记得每一段路',
        condition: { type: 'total_count', behaviorId: 'bh_run', attribute: '', value: 20 },
        rewards: { exp: 500, coins: 100 },
      },
      {
        id: 'ach_nightowl',
        name: '夜猫克星',
        icon: '🦉',
        description: '和月亮说晚安，和太阳说早安',
        condition: { type: 'total_count', behaviorId: 'bh_sleep', attribute: '', value: 14 },
        rewards: { exp: 400, coins: 120 },
      },
      {
        id: 'ach_century',
        name: '百分百',
        icon: '💯',
        description: '坚持，是这世界上最被低估的超能力',
        condition: { type: 'total_completions', behaviorId: '', attribute: '', value: 100 },
        rewards: { exp: 1000, coins: 300 },
      },
      {
        id: 'ach_lv10',
        name: '升级达人',
        icon: '📈',
        description: '你的经验条，比工资条长得快',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 10 },
        rewards: { exp: 800, coins: 200 },
      },
      {
        id: 'ach_health30',
        name: '钢铁之躯',
        icon: '🛡️',
        description: '身体是革命的本钱，你存了不少',
        condition: { type: 'attribute', behaviorId: '', attribute: 'health', value: 30 },
        rewards: { exp: 600, coins: 150 },
      },
      {
        id: 'ach_int30',
        name: '智者',
        icon: '🦉',
        description: '知识不会背叛努力的人',
        condition: { type: 'attribute', behaviorId: '', attribute: 'intelligence', value: 30 },
        rewards: { exp: 600, coins: 150 },
      },
      {
        id: 'ach_disc30',
        name: '自律即自由',
        icon: '⛓️',
        description: '你正在一寸一寸地解锁自由',
        condition: { type: 'attribute', behaviorId: '', attribute: 'discipline', value: 30 },
        rewards: { exp: 600, coins: 150 },
      },
      {
        id: 'ach_fit30',
        name: '体能觉醒',
        icon: '⚡',
        description: '每一滴汗都不会骗你',
        condition: { type: 'attribute', behaviorId: '', attribute: 'fitness', value: 30 },
        rewards: { exp: 600, coins: 150 },
      },
      // ---- 学习方面 ----
      {
        id: 'ach_read50',
        name: '读书破万卷',
        icon: '📖',
        description: '五十次阅读，你看到的世界和别人不一样了',
        condition: { type: 'total_count', behaviorId: 'bh_read', attribute: '', value: 50 },
        rewards: { exp: 800, coins: 200 },
      },
      {
        id: 'ach_read100',
        name: '藏书阁主人',
        icon: '🏛️',
        description: '一百次阅读，你的精神世界已经自带图书馆',
        condition: { type: 'total_count', behaviorId: 'bh_read', attribute: '', value: 100 },
        rewards: { exp: 2000, coins: 500 },
      },
      // ---- 运动方面 ----
      {
        id: 'ach_run50',
        name: '马拉松预备役',
        icon: '🏅',
        description: '五十次跑步，你比大多数人更懂得坚持',
        condition: { type: 'total_count', behaviorId: 'bh_run', attribute: '', value: 50 },
        rewards: { exp: 1000, coins: 250 },
      },
      {
        id: 'ach_streak7',
        name: '一周不间断',
        icon: '📅',
        description: '连续 7 天完成跑步，习惯正在变成本能',
        condition: { type: 'streak', behaviorId: 'bh_run', attribute: '', value: 7 },
        rewards: { exp: 700, coins: 180 },
      },
      {
        id: 'ach_streak30',
        name: '月度坚持者',
        icon: '🗓️',
        description: '连续 30 天完成跑步，你已经赢了昨天的自己',
        condition: { type: 'streak', behaviorId: 'bh_run', attribute: '', value: 30 },
        rewards: { exp: 3000, coins: 800 },
      },
      // ---- 生活方面 ----
      {
        id: 'ach_sleep30',
        name: '早鸟达人',
        icon: '🌅',
        description: '三十次早睡，你的生物钟比闹钟还准',
        condition: { type: 'total_count', behaviorId: 'bh_sleep', attribute: '', value: 30 },
        rewards: { exp: 900, coins: 220 },
      },
      {
        id: 'ach_sleep_streak7',
        name: '一周好眠',
        icon: '😴',
        description: '连续 7 天早睡，你的枕头是你的好朋友',
        condition: { type: 'streak', behaviorId: 'bh_sleep', attribute: '', value: 7 },
        rewards: { exp: 600, coins: 150 },
      },
      // ---- 等级方面 ----
      {
        id: 'ach_lv5',
        name: '小有进度',
        icon: '⬆️',
        description: '等级达到 Lv.5，你已经开始上道了',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 5 },
        rewards: { exp: 400, coins: 100 },
      },
      {
        id: 'ach_lv20',
        name: '等级收割机',
        icon: '🎰',
        description: '等级达到 Lv.20，你的经验条就没停过',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 20 },
        rewards: { exp: 2000, coins: 500 },
      },
      {
        id: 'ach_lv50',
        name: '半百之巅',
        icon: '🏔️',
        description: '等级达到 Lv.50，站在半山腰看风景的人',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 50 },
        rewards: { exp: 5000, coins: 1000 },
      },
      // ---- 属性方面 ----
      {
        id: 'ach_health50',
        name: '生命力旺盛',
        icon: '❤️',
        description: 'Health ≥ 50，你的血条比 Boss 还厚',
        condition: { type: 'attribute', behaviorId: '', attribute: 'health', value: 50 },
        rewards: { exp: 1200, coins: 300 },
      },
      {
        id: 'ach_int50',
        name: '博学多识',
        icon: '🎓',
        description: 'Intelligence ≥ 50，你的脑力已经溢出',
        condition: { type: 'attribute', behaviorId: '', attribute: 'intelligence', value: 50 },
        rewards: { exp: 1200, coins: 300 },
      },
      {
        id: 'ach_fit50',
        name: '钢铁肌肉',
        icon: '💪',
        description: 'Fitness ≥ 50，镜子里的你变了',
        condition: { type: 'attribute', behaviorId: '', attribute: 'fitness', value: 50 },
        rewards: { exp: 1200, coins: 300 },
      },
      {
        id: 'ach_disc50',
        name: '自律大师',
        icon: '🏹',
        description: 'Discipline ≥ 50，你说几点起就几点起',
        condition: { type: 'attribute', behaviorId: '', attribute: 'discipline', value: 50 },
        rewards: { exp: 1200, coins: 300 },
      },
      // ---- 总计方面 ----
      {
        id: 'ach_total200',
        name: '坚持不懈',
        icon: '🔄',
        description: '累计完成 200 次行为，量变正在引起质变',
        condition: { type: 'total_completions', behaviorId: '', attribute: '', value: 200 },
        rewards: { exp: 2000, coins: 500 },
      },
      {
        id: 'ach_total500',
        name: '人生玩家',
        icon: '🎮',
        description: '累计完成 500 次行为，你已经把人生玩成了 RPG',
        condition: { type: 'total_completions', behaviorId: '', attribute: '', value: 500 },
        rewards: { exp: 5000, coins: 1000 },
      },
    ],

    titles: [
      {
        id: 'ti_newbie',
        name: '初出茅庐',
        icon: '🐣',
        description: '等级达到 Lv.3',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 3 },
      },
      {
        id: 'ti_warmup',
        name: '渐入佳境',
        icon: '🌱',
        description: '等级达到 Lv.5，你开始摸到节奏了',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 5 },
      },
      {
        id: 'ti_veteran',
        name: '小有所成',
        icon: '⚔️',
        description: '等级达到 Lv.10，不再是新手，是个有故事的人',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 10 },
      },
      {
        id: 'ti_explorer',
        name: '老练冒险家',
        icon: '🛡️',
        description: '等级达到 Lv.20，你的等级条会发光',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 20 },
      },
      {
        id: 'ti_legend',
        name: '传奇玩家',
        icon: '👑',
        description: '等级达到 Lv.50，半百之路，每一步都算数',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 50 },
      },
      {
        id: 'ti_myth',
        name: '满级传说',
        icon: '🐉',
        description: '等级达到 Lv.100，百级之路，你已经走完了',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 100 },
      },
      {
        id: 'ti_learner',
        name: '终身学习者',
        icon: '🧠',
        description: 'Intelligence ≥ 50',
        condition: { type: 'attribute', behaviorId: '', attribute: 'intelligence', value: 50 },
      },
      // ---- 更多等级称号（让升级始终有期待） ----
      {
        id: 'ti_lv7',
        name: '渐入佳境',
        icon: '🌿',
        description: '等级达到 Lv.7，你开始摸到节奏了',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 7 },
      },
      {
        id: 'ti_lv15',
        name: '行家里手',
        icon: ' 🔰',
        description: '等级达到 Lv.15，你已经是个有经验的人了',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 15 },
      },
      {
        id: 'ti_lv25',
        name: '资深冒险家',
        icon: '🗺️',
        description: '等级达到 Lv.25，你的地图比别人的大了一圈',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 25 },
      },
      {
        id: 'ti_lv35',
        name: '人生老手',
        icon: '🧭',
        description: '等级达到 Lv.35，方向感十足，不容易迷路了',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 35 },
      },
      {
        id: 'ti_lv75',
        name: '超凡入圣',
        icon: '✨',
        description: '等级达到 Lv.75，凡人已经追不上你了',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 75 },
      },
      {
        id: 'ti_lv150',
        name: '不朽传说',
        icon: '🌌',
        description: '等级达到 Lv.150，你的故事会被写进史书',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 150 },
      },
      {
        id: 'ti_lv300',
        name: '永恒之主',
        icon: '♾️',
        description: '等级达到 Lv.300，时间在你面前只是数字',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 300 },
      },
      // ---- 属性称号 ----
      {
        id: 'ti_health30',
        name: '体魄强健',
        icon: '❤️‍🔥',
        description: 'Health ≥ 30，你的身体在感谢你',
        condition: { type: 'attribute', behaviorId: '', attribute: 'health', value: 30 },
      },
      {
        id: 'ti_fit30',
        name: '身轻如燕',
        icon: '🤸',
        description: 'Fitness ≥ 30，走路都带风',
        condition: { type: 'attribute', behaviorId: '', attribute: 'fitness', value: 30 },
      },
      {
        id: 'ti_disc30',
        name: '钢铁意志',
        icon: '⛓️',
        description: 'Discipline ≥ 30，说做就做，不拖泥带水',
        condition: { type: 'attribute', behaviorId: '', attribute: 'discipline', value: 30 },
      },
      {
        id: 'ti_disc100',
        name: '自律之神',
        icon: '⏳',
        description: 'Discipline ≥ 100，你的自律已经是一种信仰',
        condition: { type: 'attribute', behaviorId: '', attribute: 'discipline', value: 100 },
      },
      // ---- 总计称号 ----
      {
        id: 'ti_total100',
        name: '百战不殆',
        icon: '🎖️',
        description: '累计完成 100 次行为',
        condition: { type: 'total_completions', behaviorId: '', attribute: '', value: 100 },
      },
      {
        id: 'ti_total365',
        name: '日夜兼程',
        icon: '🌠',
        description: '累计完成 365 次行为，平均每天一次',
        condition: { type: 'total_completions', behaviorId: '', attribute: '', value: 365 },
      },
    ],
  },

  /* ---------- 描述自动补全表（按名称匹配，只填空描述，不覆盖用户写的） ---------- */
  descriptionMap: {
    behaviors: {
      '阅读': '翻开一本书，和作者来一场跨越时空的对话',
      '跑步': '系好鞋带，让风成为你的配速员',
      '早睡': '放下手机，把今天的故事交给梦境续写',
      '学习': '每一次专注，都是给未来的自己充能',
      '健身': '汗水是脂肪的眼泪',
      '冥想': '让思绪安静下来，听见内心的声音',
      '喝水': '给身体浇浇水，让它继续运转',
      '背单词': '一个单词一块砖，砌出你的语言城堡',
      '练吉他': '指尖的茧，是音乐之路的勋章',
      '做饭': '把食材变成美味，是最治愈的魔法',
      '写日记': '给今天的自己留一封信',
      '散步': '慢慢走，让思绪也跟着放个假',
      '早起': '比太阳早一步，偷走清晨的静谧',
      '学英语': '推开一扇通往另一个世界的门',
      '练琴': '每个音符都是通往自由的阶梯',
      '看书': '在别人的故事里，找自己的答案',
      '运动': '让身体记住努力的感觉',
      '练字': '一笔一划，写出安静的力量',
      '整理房间': '整理空间，也是在整理心情',
      '泡脚': '给双脚一个温暖的拥抱',
      '听播客': '用耳朵来一场思想漫游',
      '复盘': '回头看看，才能走得更远',
    },
    shopItems: {
      '听一首歌': '给耳朵发一颗糖，三分钟的 mini 假期',
      '喝奶茶': '一杯下肚，烦恼被珍珠嚼碎',
      '玩一个小时游': '一小时的虚拟冒险，把现实的烦恼暂时存档',
      '玩一个小时游戏': '一小时的虚拟冒险，把现实的烦恼暂时存档',
      '玩游戏': '按下开始键，把压力交给通关',
      '学校爽吃火锅麻辣烫': '一锅沸腾，烫熟的不只是菜，还有一整天的疲惫',
      '吃小零食': '嘴巴寂寞的时候，给它找点事情做',
      '看一场电影': '两小时的逃离现实体验券',
      '吃火锅': '围炉而坐，把所有情绪都涮进红汤里',
      '自助餐': '吃到扶墙而出，是对自助最基本的尊重',
      '足浴按摩': '让辛苦的双脚享受半小时的 VIP 待遇',
      '吃顿好的': '认真对待一顿饭，就是认真对待自己',
      '给自己买礼物': '奖励过去一段时间里那个努力的自己',
      '夏伯变调夹': '给吉他换个调，也给生活换个心情',
      '看电影': '两小时的逃离现实体验券',
      '喝奶茶': '一杯下肚，烦恼被珍珠嚼碎',
      '睡懒觉': '把闹钟关掉，让被窝的温柔多留一会儿',
      '买衣服': '给自己换个心情，也换个样子',
      '旅游': '把日子过成风景，把风景收进回忆',
      '买鞋': '脚下舒服了，路才走得远',
      '吃烧烤': '烟火气里，藏着最朴素的快乐',
      '喝可乐': '一口下去，气泡炸开的瞬间就是快乐',
      '点外卖': '不想做饭的日子，让别人来宠你',
      '买护肤品': '认真对待皮肤，是最划算的投资',
      '充会员': '跳过广告，是成年人的基本体面',
      '买游戏': '给自己开一扇通往异世界的门',
    },
  },
};
