/* ============================================================
 * LIFE RPG - 全局配置
 * 所有"可以修改"的东西都集中在这里。
 * 页面代码不会写死任何奖励数字，全部读取这里或用户自建数据。
 * ============================================================ */

const CONFIG = {
  // localStorage 存储键
  storageKey: 'life_rpg_save_v1',

  /* ---------- 等级公式（集中管理，可自行调整成长速度） ----------
   * 每级所需 EXP = round(base * growth ^ (level - 1))
   * Lv.1→2 = 1000；Lv.2→3 = 1150；Lv.3→4 = 1323 ...
   * 想改快慢：调 base（基础值）或 growth（每级倍率 1 = 不增长）
   */
  level: {
    base: 1000,
    growth: 1.15,
    maxLevel: 999,
  },

  /* ---------- 四大属性（顺序即展示顺序） ----------
   * milestone 仅为进度条展示用的参考值，可随意修改
   */
  attributes: [
    { key: 'health',        name: 'Health',        zh: '体质', icon: '❤️', color: '#ff5c7a', milestone: 100 },
    { key: 'intelligence',  name: 'Intelligence',  zh: '智力', icon: '🧠', color: '#5cc8ff', milestone: 100 },
    { key: 'fitness',       name: 'Fitness',       zh: '体能', icon: '💪', color: '#ffc24b', milestone: 100 },
    { key: 'discipline',    name: 'Discipline',    zh: '自律', icon: '🎯', color: '#b07cff', milestone: 100 },
  ],

  /* ---------- 奖励方式 ---------- */
  rewardTypes: {
    fixed:    { name: '固定奖励', desc: '每完成一次，获得固定奖励' },
    per_unit: { name: '按数量',   desc: '按填写的数量计算，例如每 1 公里' },
    per_time: { name: '按时间',   desc: '按记录的分钟数计算，例如每 30 分钟' },
  },

  /* ---------- 成就 / 称号 可用的条件类型 ---------- */
  conditionTypes: {
    first_complete:    { name: '第一次完成',   needs: ['behaviorId'],        desc: '第一次完成某个行为' },
    total_count:       { name: '累计次数',     needs: ['behaviorId', 'value'], desc: '某行为累计完成 N 次' },
    total_quantity:    { name: '累计数量',     needs: ['behaviorId', 'value'], desc: '某行为累计完成 N 个单位' },
    total_completions: { name: '累计完成所有行为', needs: ['value'],          desc: '所有行为累计完成 N 次' },
    level:             { name: '达到等级',     needs: ['value'],             desc: '玩家等级达到 Lv.N' },
    attribute:         { name: '属性达到',     needs: ['attribute', 'value'], desc: '某项属性 ≥ N' },
    streak:            { name: '连续天数',     needs: ['behaviorId', 'value'], desc: '连续 N 天完成某行为' },
  },

  /* ---------- 创建行为/商品时的快捷图标 ---------- */
  iconPresets: [
    '📖','🏃','🌙','💪','🧠','🎯','💧','🥗','🍳','🥦','⚽','🏀',
    '🏊','🚴','🚶','🏋️','🤸','🧗','⛳','🏓','🏸','🎱','✍️','💻',
    '🎨','🎸','🎹','🎤','📷','🧘','🛏️','🧹','📝','🗣️','🌱','🌸',
    '☀️','🛁','🦷','🧴','🌍','✈️','🚆','🀄','🧋','🎬','🎮','🍩',
    '🍰','☕','🍷','🍔','🍕','🍣','🍦','🛍️','🎁','🛒','💰','💎',
    '⭐','🏆','👑','🔥','🎖️','🏅','🥇','🧭','🗝️','🛡️','🐉','🌿',
    '📚','✏️','🧮','🔬','🔭','🧪','💊','🩺','⚖️','📐','📏','📋',
    '🏕️','🏖️','🚗','🏍️','⛵','🚂','🗽','🏯','🎡','🎢','🎪','🎰',
    '🐶','🐱','🐦','🐟','🌻','🍀','🔮','🪐','⚡','🌟','💫','🌙',
  ],

  /* ---------- 首次打开时的示例内容（全部可编辑/删除/重建，只是模板） ---------- */
  seed: {
    categories: [
      { id: 'cat_study',   name: '学习', icon: '📚' },
      { id: 'cat_sport',   name: '运动', icon: '🏃' },
      { id: 'cat_life',    name: '生活', icon: '🌙' },
      { id: 'cat_work',    name: '工作', icon: '💼' },
      { id: 'cat_hobby',   name: '兴趣', icon: '🎨' },
      { id: 'cat_other',   name: '其他', icon: '📦' },
    ],

    behaviors: [
      {
        id: 'bh_read',
        name: '阅读',
        categoryId: 'cat_study',
        icon: '📖',
        description: '翻开一本书，和作者来一场跨越时空的对话',
        unit: '分钟',
        rewardType: 'per_time',
        perTimeMinutes: 30,
        rewards: { exp: 20, coins: 5, health: 0, intelligence: 1, fitness: 0, discipline: 0 },
      },
      {
        id: 'bh_run',
        name: '跑步',
        categoryId: 'cat_sport',
        icon: '🏃',
        description: '系好鞋带，让风成为你的配速员',
        unit: '公里',
        rewardType: 'per_unit',
        perTimeMinutes: 30,
        rewards: { exp: 20, coins: 5, health: 0, intelligence: 0, fitness: 1, discipline: 0 },
      },
      {
        id: 'bh_sleep',
        name: '早睡',
        categoryId: 'cat_life',
        icon: '🌙',
        description: '放下手机，把今天的故事交给梦境续写',
        unit: '次',
        rewardType: 'fixed',
        perTimeMinutes: 30,
        rewards: { exp: 30, coins: 10, health: 1, intelligence: 0, fitness: 0, discipline: 2 },
      },
    ],

    shopItems: [
      { id: 'sh_song',      name: '听一首歌',           icon: '🎧', description: '给耳朵发一颗糖，三分钟的 mini 假期',       price: 10 },
      { id: 'sh_milktea',   name: '喝杯奶茶',           icon: '🧋', description: '一杯下肚，烦恼被珍珠嚼碎',                 price: 50 },
      { id: 'sh_gamehour',  name: '玩一个小时游戏',     icon: '🎮', description: '一小时的虚拟冒险，把现实的烦恼暂时存档',   price: 50 },
      { id: 'sh_hotpot_school', name: '学校爽吃火锅麻辣烫', icon: '🍲', description: '一锅沸腾，烫熟的不只是菜，还有一整天的疲惫', price: 60 },
      { id: 'sh_snack',     name: '吃小零食',           icon: '🍪', description: '嘴巴寂寞的时候，给它找点事情做',           price: 80 },
      { id: 'sh_movie',     name: '看一场电影',         icon: '🎬', description: '两小时的逃离现实体验券',                   price: 100 },
      { id: 'sh_hotpot',    name: '吃火锅',             icon: '🍲', description: '围炉而坐，把所有情绪都涮进红汤里',         price: 100 },
      { id: 'sh_buffet',    name: '自助餐',             icon: '🍽️', description: '吃到扶墙而出，是对自助最基本的尊重',       price: 100 },
      { id: 'sh_footspa',   name: '足浴按摩',           icon: '🦶', description: '让辛苦的双脚享受半小时的 VIP 待遇',        price: 200 },
      { id: 'sh_meal',      name: '吃顿好的',           icon: '🍱', description: '认真对待一顿饭，就是认真对待自己',         price: 200 },
      { id: 'sh_gift',      name: '给自己买礼物',       icon: '🎁', description: '奖励过去一段时间里那个努力的自己',         price: 300 },
      { id: 'sh_capo',      name: '夏伯变调夹',         icon: '🎸', description: '给吉他换个调，也给生活换个心情',           price: 400 },
    ],

    achievements: [
      {
        id: 'ach_first',
        name: '初来乍到',
        icon: '🌟',
        description: '旅程的起点，总是从第一步开始',
        condition: { type: 'total_completions', behaviorId: '', attribute: '', value: 1 },
        rewards: { exp: 100, coins: 20 },
      },
      {
        id: 'ach_read10',
        name: '读书入门',
        icon: '📚',
        description: '十次翻开书本，世界比昨天大了一点点',
        condition: { type: 'total_count', behaviorId: 'bh_read', attribute: '', value: 10 },
        rewards: { exp: 200, coins: 50 },
      },
      {
        id: 'ach_streak3',
        name: '三日之约',
        icon: '🔥',
        description: '连续三天，你已经和惰性交过手并赢了',
        condition: { type: 'streak', behaviorId: 'bh_run', attribute: '', value: 3 },
        rewards: { exp: 300, coins: 80 },
      },
      {
        id: 'ach_bookworm',
        name: '书虫',
        icon: '🐛',
        description: '书架在变厚，大脑也在变厚',
        condition: { type: 'total_count', behaviorId: 'bh_read', attribute: '', value: 30 },
        rewards: { exp: 500, coins: 100 },
      },
      {
        id: 'ach_runner',
        name: '跑者',
        icon: '👟',
        description: '你的鞋底记得每一段路',
        condition: { type: 'total_count', behaviorId: 'bh_run', attribute: '', value: 20 },
        rewards: { exp: 500, coins: 100 },
      },
      {
        id: 'ach_nightowl',
        name: '夜猫克星',
        icon: '🦉',
        description: '和月亮说晚安，和太阳说早安',
        condition: { type: 'total_count', behaviorId: 'bh_sleep', attribute: '', value: 14 },
        rewards: { exp: 400, coins: 120 },
      },
      {
        id: 'ach_century',
        name: '百分百',
        icon: '💯',
        description: '坚持，是这世界上最被低估的超能力',
        condition: { type: 'total_completions', behaviorId: '', attribute: '', value: 100 },
        rewards: { exp: 1000, coins: 300 },
      },
      {
        id: 'ach_lv10',
        name: '升级达人',
        icon: '📈',
        description: '你的经验条，比工资条长得快',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 10 },
        rewards: { exp: 800, coins: 200 },
      },
      {
        id: 'ach_health30',
        name: '钢铁之躯',
        icon: '🛡️',
        description: '身体是革命的本钱，你存了不少',
        condition: { type: 'attribute', behaviorId: '', attribute: 'health', value: 30 },
        rewards: { exp: 600, coins: 150 },
      },
      {
        id: 'ach_int30',
        name: '智者',
        icon: '🦉',
        description: '知识不会背叛努力的人',
        condition: { type: 'attribute', behaviorId: '', attribute: 'intelligence', value: 30 },
        rewards: { exp: 600, coins: 150 },
      },
      {
        id: 'ach_disc30',
        name: '自律即自由',
        icon: '⛓️',
        description: '你正在一寸一寸地解锁自由',
        condition: { type: 'attribute', behaviorId: '', attribute: 'discipline', value: 30 },
        rewards: { exp: 600, coins: 150 },
      },
      {
        id: 'ach_fit30',
        name: '体能觉醒',
        icon: '⚡',
        description: '每一滴汗都不会骗你',
        condition: { type: 'attribute', behaviorId: '', attribute: 'fitness', value: 30 },
        rewards: { exp: 600, coins: 150 },
      },
      // ---- 学习方面 ----
      {
        id: 'ach_read50',
        name: '读书破万卷',
        icon: '📖',
        description: '五十次阅读，你看到的世界和别人不一样了',
        condition: { type: 'total_count', behaviorId: 'bh_read', attribute: '', value: 50 },
        rewards: { exp: 800, coins: 200 },
      },
      {
        id: 'ach_read100',
        name: '藏书阁主人',
        icon: '🏛️',
        description: '一百次阅读，你的精神世界已经自带图书馆',
        condition: { type: 'total_count', behaviorId: 'bh_read', attribute: '', value: 100 },
        rewards: { exp: 2000, coins: 500 },
      },
      // ---- 运动方面 ----
      {
        id: 'ach_run50',
        name: '马拉松预备役',
        icon: '🏅',
        description: '五十次跑步，你比大多数人更懂得坚持',
        condition: { type: 'total_count', behaviorId: 'bh_run', attribute: '', value: 50 },
        rewards: { exp: 1000, coins: 250 },
      },
      {
        id: 'ach_streak7',
        name: '一周不间断',
        icon: '📅',
        description: '连续 7 天完成跑步，习惯正在变成本能',
        condition: { type: 'streak', behaviorId: 'bh_run', attribute: '', value: 7 },
        rewards: { exp: 700, coins: 180 },
      },
      {
        id: 'ach_streak30',
        name: '月度坚持者',
        icon: '🗓️',
        description: '连续 30 天完成跑步，你已经赢了昨天的自己',
        condition: { type: 'streak', behaviorId: 'bh_run', attribute: '', value: 30 },
        rewards: { exp: 3000, coins: 800 },
      },
      // ---- 生活方面 ----
      {
        id: 'ach_sleep30',
        name: '早鸟达人',
        icon: '🌅',
        description: '三十次早睡，你的生物钟比闹钟还准',
        condition: { type: 'total_count', behaviorId: 'bh_sleep', attribute: '', value: 30 },
        rewards: { exp: 900, coins: 220 },
      },
      {
        id: 'ach_sleep_streak7',
        name: '一周好眠',
        icon: '😴',
        description: '连续 7 天早睡，你的枕头是你的好朋友',
        condition: { type: 'streak', behaviorId: 'bh_sleep', attribute: '', value: 7 },
        rewards: { exp: 600, coins: 150 },
      },
      // ---- 等级方面 ----
      {
        id: 'ach_lv5',
        name: '小有进度',
        icon: '⬆️',
        description: '等级达到 Lv.5，你已经开始上道了',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 5 },
        rewards: { exp: 400, coins: 100 },
      },
      {
        id: 'ach_lv20',
        name: '等级收割机',
        icon: '🎰',
        description: '等级达到 Lv.20，你的经验条就没停过',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 20 },
        rewards: { exp: 2000, coins: 500 },
      },
      {
        id: 'ach_lv50',
        name: '半百之巅',
        icon: '🏔️',
        description: '等级达到 Lv.50，站在半山腰看风景的人',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 50 },
        rewards: { exp: 5000, coins: 1000 },
      },
      // ---- 属性方面 ----
      {
        id: 'ach_health50',
        name: '生命力旺盛',
        icon: '❤️',
        description: 'Health ≥ 50，你的血条比 Boss 还厚',
        condition: { type: 'attribute', behaviorId: '', attribute: 'health', value: 50 },
        rewards: { exp: 1200, coins: 300 },
      },
      {
        id: 'ach_int50',
        name: '博学多识',
        icon: '🎓',
        description: 'Intelligence ≥ 50，你的脑力已经溢出',
        condition: { type: 'attribute', behaviorId: '', attribute: 'intelligence', value: 50 },
        rewards: { exp: 1200, coins: 300 },
      },
      {
        id: 'ach_fit50',
        name: '钢铁肌肉',
        icon: '💪',
        description: 'Fitness ≥ 50，镜子里的你变了',
        condition: { type: 'attribute', behaviorId: '', attribute: 'fitness', value: 50 },
        rewards: { exp: 1200, coins: 300 },
      },
      {
        id: 'ach_disc50',
        name: '自律大师',
        icon: '🏹',
        description: 'Discipline ≥ 50，你说几点起就几点起',
        condition: { type: 'attribute', behaviorId: '', attribute: 'discipline', value: 50 },
        rewards: { exp: 1200, coins: 300 },
      },
      // ---- 总计方面 ----
      {
        id: 'ach_total200',
        name: '坚持不懈',
        icon: '🔄',
        description: '累计完成 200 次行为，量变正在引起质变',
        condition: { type: 'total_completions', behaviorId: '', attribute: '', value: 200 },
        rewards: { exp: 2000, coins: 500 },
      },
      {
        id: 'ach_total500',
        name: '人生玩家',
        icon: '🎮',
        description: '累计完成 500 次行为，你已经把人生玩成了 RPG',
        condition: { type: 'total_completions', behaviorId: '', attribute: '', value: 500 },
        rewards: { exp: 5000, coins: 1000 },
      },
    ],

    titles: [
      {
        id: 'ti_newbie',
        name: '初出茅庐',
        icon: '🐣',
        description: '等级达到 Lv.3',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 3 },
      },
      {
        id: 'ti_warmup',
        name: '渐入佳境',
        icon: '🌱',
        description: '等级达到 Lv.5，你开始摸到节奏了',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 5 },
      },
      {
        id: 'ti_veteran',
        name: '小有所成',
        icon: '⚔️',
        description: '等级达到 Lv.10，不再是新手，是个有故事的人',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 10 },
      },
      {
        id: 'ti_explorer',
        name: '老练冒险家',
        icon: '🛡️',
        description: '等级达到 Lv.20，你的等级条会发光',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 20 },
      },
      {
        id: 'ti_legend',
        name: '传奇玩家',
        icon: '👑',
        description: '等级达到 Lv.50，半百之路，每一步都算数',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 50 },
      },
      {
        id: 'ti_myth',
        name: '满级传说',
        icon: '🐉',
        description: '等级达到 Lv.100，百级之路，你已经走完了',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 100 },
      },
      {
        id: 'ti_learner',
        name: '终身学习者',
        icon: '🧠',
        description: 'Intelligence ≥ 50',
        condition: { type: 'attribute', behaviorId: '', attribute: 'intelligence', value: 50 },
      },
      // ---- 更多等级称号（让升级始终有期待） ----
      {
        id: 'ti_lv7',
        name: '渐入佳境',
        icon: '🌿',
        description: '等级达到 Lv.7，你开始摸到节奏了',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 7 },
      },
      {
        id: 'ti_lv15',
        name: '行家里手',
        icon: ' 🔰',
        description: '等级达到 Lv.15，你已经是个有经验的人了',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 15 },
      },
      {
        id: 'ti_lv25',
        name: '资深冒险家',
        icon: '🗺️',
        description: '等级达到 Lv.25，你的地图比别人的大了一圈',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 25 },
      },
      {
        id: 'ti_lv35',
        name: '人生老手',
        icon: '🧭',
        description: '等级达到 Lv.35，方向感十足，不容易迷路了',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 35 },
      },
      {
        id: 'ti_lv75',
        name: '超凡入圣',
        icon: '✨',
        description: '等级达到 Lv.75，凡人已经追不上你了',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 75 },
      },
      {
        id: 'ti_lv150',
        name: '不朽传说',
        icon: '🌌',
        description: '等级达到 Lv.150，你的故事会被写进史书',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 150 },
      },
      {
        id: 'ti_lv300',
        name: '永恒之主',
        icon: '♾️',
        description: '等级达到 Lv.300，时间在你面前只是数字',
        condition: { type: 'level', behaviorId: '', attribute: '', value: 300 },
      },
      // ---- 属性称号 ----
      {
        id: 'ti_health30',
        name: '体魄强健',
        icon: '❤️‍🔥',
        description: 'Health ≥ 30，你的身体在感谢你',
        condition: { type: 'attribute', behaviorId: '', attribute: 'health', value: 30 },
      },
      {
        id: 'ti_fit30',
        name: '身轻如燕',
        icon: '🤸',
        description: 'Fitness ≥ 30，走路都带风',
        condition: { type: 'attribute', behaviorId: '', attribute: 'fitness', value: 30 },
      },
      {
        id: 'ti_disc30',
        name: '钢铁意志',
        icon: '⛓️',
        description: 'Discipline ≥ 30，说做就做，不拖泥带水',
        condition: { type: 'attribute', behaviorId: '', attribute: 'discipline', value: 30 },
      },
      {
        id: 'ti_disc100',
        name: '自律之神',
        icon: '⏳',
        description: 'Discipline ≥ 100，你的自律已经是一种信仰',
        condition: { type: 'attribute', behaviorId: '', attribute: 'discipline', value: 100 },
      },
      // ---- 总计称号 ----
      {
        id: 'ti_total100',
        name: '百战不殆',
        icon: '🎖️',
        description: '累计完成 100 次行为',
        condition: { type: 'total_completions', behaviorId: '', attribute: '', value: 100 },
      },
      {
        id: 'ti_total365',
        name: '日夜兼程',
        icon: '🌠',
        description: '累计完成 365 次行为，平均每天一次',
        condition: { type: 'total_completions', behaviorId: '', attribute: '', value: 365 },
      },
    ],
  },

  /* ---------- 描述自动补全表（按名称匹配，只填空描述，不覆盖用户写的） ---------- */
  descriptionMap: {
    behaviors: {
      '阅读': '翻开一本书，和作者来一场跨越时空的对话',
      '跑步': '系好鞋带，让风成为你的配速员',
      '早睡': '放下手机，把今天的故事交给梦境续写',
      '学习': '每一次专注，都是给未来的自己充能',
      '健身': '汗水是脂肪的眼泪',
      '冥想': '让思绪安静下来，听见内心的声音',
      '喝水': '给身体浇浇水，让它继续运转',
      '背单词': '一个单词一块砖，砌出你的语言城堡',
      '练吉他': '指尖的茧，是音乐之路的勋章',
      '做饭': '把食材变成美味，是最治愈的魔法',
      '写日记': '给今天的自己留一封信',
      '散步': '慢慢走，让思绪也跟着放个假',
      '早起': '比太阳早一步，偷走清晨的静谧',
      '学英语': '推开一扇通往另一个世界的门',
      '练琴': '每个音符都是通往自由的阶梯',
      '看书': '在别人的故事里，找自己的答案',
      '运动': '让身体记住努力的感觉',
      '练字': '一笔一划，写出安静的力量',
      '整理房间': '整理空间，也是在整理心情',
      '泡脚': '给双脚一个温暖的拥抱',
      '听播客': '用耳朵来一场思想漫游',
      '复盘': '回头看看，才能走得更远',
      '晨跑': '用脚步丈量清晨，和太阳一起出发',
      '夜跑': '在夜色里奔跑，把一天的疲惫甩在身后',
      '游泳': '在水里，所有的烦恼都变得轻飘飘',
      '骑行': '风在耳边唱歌，路在脚下延伸',
      '瑜伽': '在呼吸之间，找到身心的平衡',
      '跳绳': '一下一下，跳出轻盈的自己',
      '举铁': '每一次举起，都是对软弱的告别',
      '打篮球': '球场上，所有的不快都能被汗水冲走',
      '打羽毛球': '球拍一挥，把烦恼打回对方场地',
      '爬山': '站在山顶，才懂什么叫值得',
      '洗衣服': '洗去的不只是污渍，还有一天的疲惫',
      '打扫卫生': '干净的环境，才能装下干净的心情',
      '洗碗': '水流过指尖，把烦恼也一并冲走',
      '叠被子': '给清晨一个仪式感，告诉自己今天也要好好过',
      '记账': '每一笔数字，都是认真生活的证据',
      '存钱': '今天的克制，是明天的自由',
      '学编程': '用代码搭建属于自己的世界',
      '写代码': '每一行代码，都是创造力的延伸',
      '练口语': '开口的那一刻，你已经赢了',
      '听力': '竖起耳朵，捕捉世界的细节',
      '看纪录片': '用别人的镜头，看自己没去过的世界',
      '看网课': '屏幕虽小，世界很大',
      '刷题': '每一道题，都是通往目标的台阶',
      '写作': '把脑子里的想法，变成纸上的风景',
      '画画': '用色彩和线条，画出心里的世界',
      '摄影': '用镜头，定格稍纵即逝的美好',
      '学乐器': '让乐器替你说出那些说不出的话',
      '练唱歌': '跑调也没关系，快乐才是主旋律',
      '学日语': '多一种语言，多一个世界',
      '学韩语': '追星的路上，没有字幕也能听懂',
      '练书法': '墨香里，藏着古人的智慧',
      '读书': '在别人的故事里，找自己的答案',
      '看小说': '用别人的人生，丰富自己的阅历',
      '看漫画': '二次元的世界，永远有热血和感动',
      '写作业': '今天的作业，是明天的底气',
      '复习': '温故而知新，老祖宗说得对',
      '预习': '比别人早一步，就多一分从容',
      '考试': '检验自己的时刻，放轻松',
      '加班': '多干一点，离目标近一点',
      '工作': '认真工作的人，最酷',
      '开会': '思想碰撞的地方，灵感可能就在下一秒',
      '通勤': '路上的时间，也是属于自己的时光',
      '午休': '给大脑充个电，下午再战',
      '午睡': '二十分钟的小憩，换来一下午的清醒',
      '吃早餐': '好好吃早餐，是对胃最基本的尊重',
      '吃水果': '给身体补充维生素，也补充好心情',
      '吃蔬菜': '绿色的力量，让身体更轻盈',
      '不喝奶茶': '忍住的每一口，都是自律的勋章',
      '不吃零食': '嘴巴忍一忍，身材会感谢你',
      '不熬夜': '早睡的人，运气不会太差',
      '不刷手机': '放下手机，发现身边的美好',
      '冥想10分钟': '十分钟的安静，换一整天的清明',
      '深呼吸': '吸气，呼气，烦恼都随气息散去',
      '晒太阳': '让阳光照进心里，驱散所有阴霾',
      '晒太阳补钙': '免费的营养，别浪费',
      '洗澡': '洗去一身疲惫，换一个全新的自己',
      '护肤': '认真对待皮肤，时间会回报你',
      '敷面膜': '十五分钟的放松，给皮肤一次深呼吸',
      '剪指甲': '小细节，大不同',
      '理发': '换个发型，换种心情',
      '买花': '给自己的生活，添一抹色彩',
      '养植物': '看着它慢慢长大，治愈又有成就感',
      '遛狗': '它陪你散步，你陪它快乐',
      '撸猫': '猫主子的毛，是最好的解压神器',
      '和朋友聊天': '有些话，说出来就好了',
      '打电话给家人': '一句问候，胜过千言万语',
      '看剧': '用别人的故事，放松自己的心情',
      '追剧': '每周的期待，是生活的小确幸',
      '看综艺': '笑一笑，十年少',
      '打游戏': '在虚拟世界里，做现实中不敢做的事',
      '听音乐': '音乐是情绪的出口',
      '听相声': '乐呵乐呵，烦恼就散了',
      '看相声': '乐呵乐呵，烦恼就散了',
      '整理衣柜': '扔掉不需要的，留下真正喜欢的',
      '断舍离': '放下，才能拥有更多',
      '整理书桌': '整洁的桌面，是高效的开始',
      '清手机内存': '删删减减，给手机也给自己留空间',
      '回消息': '别让在乎你的人等太久',
      '写周报': '记录成长，也记录困惑',
      '做计划': '有计划的一天，不会跑偏',
      '列清单': '打勾的那一刻，成就感爆棚',
      '做总结': '总结不是结束，是新的开始',
      '学理财': '你不理财，财不理你',
      '看财报': '看懂数字背后的故事',
      '学投资': '让钱为你工作，而不是你为钱工作',
      '买基金': '长期主义，是普通人最好的投资',
      '学摄影': '美无处不在，缺的是发现美的眼睛',
      '修图': '把普通的照片，变成艺术品',
      '剪辑视频': '用镜头讲述你的故事',
      '学设计': '好的设计，让世界更美好',
      '做PPT': '每一页，都是表达的艺术',
      '学Excel': '表格玩得溜，效率翻倍',
      '学PS': '像素之间，藏着无限可能',
      '学AI': '跟上时代，别被抛下',
      '写博客': '记录思考，留下痕迹',
      '发朋友圈': '分享生活，也是一种热爱',
      '学做饭': '厨房里，藏着最温暖的人间烟火',
      '学烘焙': '烤箱打开的那一刻，满屋都是幸福',
      '学做菜': '学会一道菜，就多一个爱自己的理由',
      '打扫厨房': '干净的厨房，才能做出好吃的饭',
      '倒垃圾': '倒掉的不只是垃圾，还有坏心情',
      '取快递': '拆快递的快乐，谁懂啊',
      '拿外卖': '干饭人，干饭魂',
    },
    shopItems: {
      '听一首歌': '给耳朵发一颗糖，三分钟的 mini 假期',
      '喝奶茶': '一杯下肚，烦恼被珍珠嚼碎',
      '喝杯奶茶': '一杯下肚，烦恼被珍珠嚼碎',
      '玩一个小时游': '一小时的虚拟冒险，把现实的烦恼暂时存档',
      '玩一个小时游戏': '一小时的虚拟冒险，把现实的烦恼暂时存档',
      '玩游戏': '按下开始键，把压力交给通关',
      '游戏时间': '按下开始键，把压力交给通关',
      '学校爽吃火锅麻辣烫': '一锅沸腾，烫熟的不只是菜，还有一整天的疲惫',
      '吃小零食': '嘴巴寂寞的时候，给它找点事情做',
      '看一场电影': '两小时的逃离现实体验券',
      '吃火锅': '围炉而坐，把所有情绪都涮进红汤里',
      '自助餐': '吃到扶墙而出，是对自助最基本的尊重',
      '足浴按摩': '让辛苦的双脚享受半小时的 VIP 待遇',
      '吃顿好的': '认真对待一顿饭，就是认真对待自己',
      '给自己买礼物': '奖励过去一段时间里那个努力的自己',
      '夏伯变调夹': '给吉他换个调，也给生活换个心情',
      '看电影': '两小时的逃离现实体验券',
      '睡懒觉': '把闹钟关掉，让被窝的温柔多留一会儿',
      '买衣服': '给自己换个心情，也换个样子',
      '旅游': '把日子过成风景，把风景收进回忆',
      '旅行': '把日子过成风景，把风景收进回忆',
      '买鞋': '脚下舒服了，路才走得远',
      '吃烧烤': '烟火气里，藏着最朴素的快乐',
      '喝可乐': '一口下去，气泡炸开的瞬间就是快乐',
      '点外卖': '不想做饭的日子，让别人来宠你',
      '买护肤品': '认真对待皮肤，是最划算的投资',
      '充会员': '跳过广告，是成年人的基本体面',
      '买游戏': '给自己开一扇通往异世界的门',
      '买奶茶': '一杯下肚，烦恼被珍珠嚼碎',
      '吃冰淇淋': '冰凉的甜，是夏天最好的解药',
      '吃蛋糕': '一口下去，所有不开心都被奶油融化',
      '买咖啡': '一杯咖啡，唤醒还没醒的灵魂',
      '喝咖啡': '一杯咖啡，唤醒还没醒的灵魂',
      '看演唱会': '在人海里，和喜欢的歌手一起唱歌',
      '买专辑': '把喜欢的音乐，收藏进自己的世界',
      '买周边': '为爱发电，快乐加倍',
      '买玩具': '大人也需要玩具，来治愈生活',
      '买手办': '把喜欢的角色，留在身边',
      '买盲盒': '拆盒的惊喜，是成年人的小确幸',
      '做美甲': '指尖的美丽，也是一种态度',
      '做头发': '换个发型，换种心情面对生活',
      '做SPA': '给身体一次彻底的放松',
      '按摩': '让僵硬的身体，重新变得柔软',
      '汗蒸': '流一身汗，把毒素和烦恼都排出去',
      '泡澡': '泡在温水里，世界都安静了',
      '买花': '给自己的生活，添一抹色彩和香气',
      '买绿植': '养一盆植物，也养一份心情',
      '买书': '买书如山倒，读书如抽丝，但书是最好的投资',
      '买文具': '好看的文具，让学习也变得开心',
      '买包包': '包治百病，心情不好就买包',
      '买化妆品': '化妆不是为了别人，是为了取悦自己',
      '买香水': '好闻的味道，会留在别人的记忆里',
      '吃日料': '精致的日料，是对味蕾的犒赏',
      '吃烤肉': '滋滋作响的烤肉，是人间最美的声音',
      '吃寿司': '一口一个，把大海的味道装进嘴里',
      '吃披萨': '拉丝的芝士，拉出长长的快乐',
      '吃汉堡': '大口咬下去，满足感爆棚',
      '吃炸鸡': '酥脆的外皮，是快乐的声音',
      '吃甜品': '生活有点苦，需要甜品来中和',
      '吃巧克力': '黑巧的苦，回甘是甜',
      '买相机': '用更好的镜头，记录更好的生活',
      '买耳机': '好耳机，让音乐有了新的生命',
      '买键盘': '码字人的快乐，一把好键盘就够了',
      '买鼠标': '顺手的工具，让效率翻倍',
      '买显示器': '大屏的快乐，谁用谁知道',
      '买手机': '新手机，新开始',
      '买电脑': '生产力工具，值得投资',
      '买平板': '追剧画画记笔记，一个就够了',
      '买Switch': '游戏党的快乐老家',
      '买PS5': '画质拉满，沉浸感爆棚',
      '买Steam游戏': '喜加一的快乐，不玩也要买',
      '看脱口秀': '笑到肚子疼，是最好的解压',
      '看话剧': '舞台上的人生，比想象中更动人',
      '看展览': '在艺术里，慢下来',
      '去博物馆': '和历史对话，和文明握手',
      '去游乐园': '做一天小孩，无忧无虑',
      '去动物园': '看看动物们，治愈所有不开心',
      '去海边': '大海那么大，能装下所有烦恼',
      '去爬山': '山顶的风景，值得一路的汗水',
      '去露营': '在星空下睡觉，在鸟鸣中醒来',
      '去野餐': '草地上的美食，格外好吃',
      '买零食大礼包': '一整包的快乐，慢慢吃',
      '买水果': '甜甜的水果，甜甜的一天',
      '买牛奶': '每天一杯奶，强壮中国人',
      '买酸奶': '益生菌的关怀，肠胃知道',
      '看动漫': '二次元的世界，永远有热血和感动',
      '追番': '每周的期待，是生活的小确幸',
      '看小说': '在别人的故事里，体验不一样的人生',
      '买漫画': '收藏的不是书，是青春',
      '买轻小说': '轻小说的世界，轻松又治愈',
      '学游泳': '在水里，所有的烦恼都变得轻飘飘',
      '学滑雪': '雪地上飞驰的感觉，会上瘾',
      '学冲浪': '和海浪共舞，是自由的味道',
      '学攀岩': '每向上一步，都在挑战自己的极限',
      '学潜水': '潜入深蓝，遇见另一个世界',
      '买吉他': '六根弦，能弹出整个青春',
      '买钢琴': '八十八个键，奏出人生的喜怒哀乐',
      '买尤克里里': '小小的身材，大大的快乐',
      '买口琴': '口袋里的乐器，随时来一曲',
      '买笛子': '笛声悠扬，思绪飘远',
      '买书': '书是最便宜的奢侈品',
      '买Kindle': '把图书馆装进口袋',
      '买电子书': '随时随地，想读就读',
      '买台灯': '一盏好灯，照亮每个奋斗的夜晚',
      '买椅子': '久坐的人，需要一把好椅子',
      '买桌子': '属于自己的一方小天地',
      '买收纳盒': '井井有条，是治愈强迫症的良药',
      '买香薰': '好闻的味道，让家更有温度',
      '买蜡烛': '烛光摇曳，浪漫就有了',
      '买地毯': '光脚踩上去，幸福感爆棚',
      '买抱枕': '软乎乎的抱枕，是沙发的灵魂',
      '买拖鞋': '回家换上拖鞋，整个人都放松了',
      '买睡衣': '舒服的睡衣，是对睡眠最基本的尊重',
      '买袜子': '小小的袜子，大大的温暖',
      '买内衣': '贴身的舒适，只有自己知道',
      '买帽子': '不洗头的救命稻草，也是时尚单品',
      '买围巾': '冬天的温暖，从一条围巾开始',
      '买手套': '手暖和了，心也暖和了',
      '买墨镜': '帅不帅，一副墨镜说了算',
      '买手表': '时间的陪伴，是最长情的告白',
      '买项链': '贴近心口的装饰，是爱自己的方式',
      '买戒指': '圈住的不是手指，是幸福',
      '买耳环': '耳朵上的风景，点缀整个look',
      '买手链': '手腕间的灵动，是细节的浪漫',
    },
  },
};
